### ISSUE TITLE
urls are not shortened when publishing

### ISSUE THREAD

**Issue by talgalili** [joedolson/wp-to-twitter#3]
Hi,
I'm using the most recent WP (5.2.1) and wp to twitter (3.3.12).
Since recently upgrading, the twits I get are without the wp url shortener (see here: https://twitter.com/rbloggers), even though I have it turned on as before.
They only get shortened if I manually go to the post and re-send the tweet again.

Could you please advise/fix?

Thanks.

**Comment by joedolson** [comment]
They look shortened to me, based on a glance at your Twitter timeline. I'll also note that URL shorteners have been pretty much irrelevant on Twitter for years. The "real" URL on Twitter is always a t.co shortened URL, and they're all the same length. The URL (shortened or not) that you send is only used for display.

**Comment by talgalili** [comment]
Hey,
1) I'm using wp for shortening, and that's worked before and now it stopped.
2) When using it, there is a t.co that redirects to wp which redirects to the site.
3) The reason I care about it is because the t.co url has ?amp=1 (which is causing some issues with my configuration, and is not a problem when going through the long redirect route). So I personally would hope to have it fixed (but feel free not to, if you don't find it important)

Cheers, 
T

**Comment by joedolson** [comment]
I'm not really clear on exactly how these aren't working; I can't see any examples in your Twitter timeline (going back to late May) that don't display a shortened URL. I have no way of knowing, of course, if you replaced a Tweet manually. Regardless, I'm simply not certain what the issue is here. 

I can't do anything about Twitter's usage of the AMP parameters; that's generated based on the source code of your page, which includes the amphtml tags. If you eliminate the amphtml tags on your site, you won't have that problem.
